Fix issue #30
PowerShell/JEA pull request #46
Opened 2018-05-10 13:34 UTC by jnury

Hello,

This is my fix proposal for issue #30.

Before registering the PSSessionConfiguration, we save the list of services running in the same process as WinRM + services depending from them.

We let Register-PSSessionConfiguration command 10 seconds to complete. If it not complete in 10 seconds and the WinRM service is in the state 'Stopping', we kill the process hosting WinRm service and then restart all services impacted.

2018-05-14 04:57 UTC, rpsqrd commented
Thanks Julien -- I'll take a closer look this week and get this merged in. How would we suggest people opt out of this feature if they don't want the risk of killing the process? Set the timeout to `[int]::MaxValue` or `null`?

2018-05-14 07:46 UTC, jnury commented
Hello Ryan,
You are right, we need an option to opt out. I think setting the timeout to
0 is the most intuitive way.
I’ll modify my PR the next weekend.
Have a nice day.

On Mon, 14 May 2018 at 05:57, Ryan Puffer <notifications@github.com> wrote:

> Thanks Julien -- I'll take a closer look this week and get this merged in.
> How would we suggest people opt out of this feature if they don't want the
> risk of killing the process? Set the timeout to [int]::MaxValue or null?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PowerShell/JEA/pull/46#issuecomment-388697191>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AI4kpGDf3w8-7dHz6RoMg3dri3rW_kv-ks5tyQ7LgaJpZM4T55oi>
> .
>

2018-05-20 15:50 UTC, jnury commented
Disabling WinRM workaround (process killing) is implemented: when HungRegistrationTimeout is set to 0, no process is killed.

2018-07-06 20:14 UTC, TravisEz13 commented on DSC Resource/JustEnoughAdministration/JustEnoughAdministration.psm1
> +            $Global:VerbosePreference = 'SilentlyContinue'
Can this be changed to the script scope?

2018-07-06 20:14 UTC, TravisEz13 commented on DSC Resource/JustEnoughAdministration/JustEnoughAdministration.psm1
> +            $Global:VerbosePreference = 'SilentlyContinue'
same scope issue

2018-07-06 20:17 UTC, TravisEz13 commented on DSC Resource/JustEnoughAdministration/JustEnoughAdministration.psm1
> +                $registerString = "`$null = Register-PSSessionConfiguration -Name '$Name' -Path '$Path' -Force -ErrorAction 'Stop' -WarningAction 'SilentlyContinue'"
Can we use a static script block with paramenters and the argument list to Start-job?

2018-07-06 20:17 UTC, TravisEz13 requested changes
see comments

2023-10-18 18:47 UTC, closed without merging